Repository openscilab/mybutton, pull requests merged in 2024-12, with the labels that each got.

#50 New Services & 404 Page
  .github/404.html
  CHANGELOG.md
  README.md
  otherfiles/logo-without-name.svg
  src/Assets/icons/services/hacker-news.svg
  src/Assets/icons/services/yahoo.svg
  src/Assets/less/rsuite.config.less
  src/Assets/scss/base/colors.scss
  src/Data/services.data.ts
  src/Views/Layout/ShareModal/index.scss
  tailwind.config.js
Labels: enhancement, new service

#57 Fix/`undefined` href bug
  src/Data/services.data.ts
  src/Views/Pages/GetButton/index.tsx
Labels: bug

#58 Minor edits
  CHANGELOG.md
  README.md
Labels: documentation

#59 Version 0.4
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  SECURITY.md
  otherfiles/version_check.py
  package.json
  src/App/Config/constants.ts
Labels: release
