Repository openscilab/mybutton, pull requests merged in 2024-10, with the labels that each got.

#39 Improve encoding
  src/Views/Layout/ShareModal/index.tsx
  src/Views/Pages/GetButton/index.tsx
Labels: enhancement

#40 New services
  CHANGELOG.md
  src/Assets/icons/services/whatsapp.svg
  src/Assets/icons/services/x.svg
  src/Components/Loader/index.scss
  src/Components/Loader/index.tsx
  src/Components/LoadingCover.tsx
  src/Data/services.data.ts
  src/Views/Layout/ShareModal/index.scss
  src/Views/Layout/ShareModal/index.tsx
  src/Views/Pages/GetButton/index.scss
  src/Views/Pages/GetButton/index.tsx
  src/Views/Pages/Share/index.tsx
Labels: enhancement, new service

#42 Add/google analytics
  CHANGELOG.md
  public/index.html
Labels: enhancement, new feature

#43 Version 0.3
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  SECURITY.md
  otherfiles/version_check.py
  package.json
  src/App/Config/constants.ts
Labels: release

#44 Minor fix
  CHANGELOG.md
  README.md
  src/Data/services.data.ts
Labels: enhancement, fix
