Repository openscilab/mybutton, pull requests merged in 2024-09, with the labels that each got.

#29 Fix/query param support
  src/App/Routes/routes.tsx
  src/Assets/icons/circles.svg
  src/Assets/icons/loader.svg
  src/Assets/icons/loading.svg
  src/Components/LoadingCover.tsx
  src/Tools/Hooks/useLocalCache/index.ts
  src/Tools/Store/actions/LocalCacheActions.ts
  src/Tools/Store/index.tsx
  src/Tools/Store/reducers/LocalCacheReducer.ts
  src/Tools/Store/slices/LocalCacheSlice.ts
  src/Tools/Store/slices/index.ts
  src/Views/Layout/Navbar/NavBar.scss
  src/Views/Layout/Navbar/NavBar.tsx
  src/Views/Layout/ShareModal/index.tsx
  src/Views/Layout/index.tsx
  src/Views/Pages/GetButton/index.scss
  src/Views/Pages/GetButton/index.tsx
  src/Views/Pages/Home/index.tsx
  src/Views/Pages/PagesRouter.tsx
  src/Views/Pages/router.tsx
Labels: bug, fix

#30 Version 0.2
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  SECURITY.md
  otherfiles/version_check.py
  package.json
  src/App/Config/constants.ts
Labels: release

#31 move build & version_check steps to github runners
  .github/workflows/dev.yaml
  CHANGELOG.md
Labels: enhancement

#37 Fix/multi parameters
  src/Views/Layout/ShareModal/index.tsx
  src/Views/Pages/GetButton/index.tsx
  src/Views/Pages/Share/index.tsx
Labels: bug

#38 Authors
  AUTHORS.md
  CHANGELOG.md
Labels: documentation
