Repository openscilab/mybutton, pull requests merged in 2025-01, with the labels that each got.

#60 Minor edit
  public/404.html
Labels: bug

#61 Enhancement/custom share
  src/Views/Layout/Navbar/NavBar.tsx
  src/Views/Layout/ShareModal/index.tsx
  src/Views/Layout/index.tsx
Labels: enhancement, new feature

#63 Feature/new services
  CHANGELOG.md
  src/Assets/icons/services/blogger.svg
  src/Assets/icons/services/facebook.svg
  src/Assets/icons/services/linkedin.svg
  src/Assets/icons/services/pinterest.svg
  src/Assets/icons/services/reddit.svg
  src/Assets/icons/services/trello.svg
  src/Data/services.data.ts
  src/Views/Layout/ShareModal/index.scss
  src/Views/Pages/GetButton/index.scss
Labels: new service

#62 Version 0.5
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  otherfiles/version_check.py
  package.json
  src/App/Config/constants.ts
Labels: release

#66 Update/GitHub action version
  .github/workflows/dev.yaml
  .github/workflows/prod.yaml
  CHANGELOG.md
Labels: enhancement

#65 Refactor/naming
  CHANGELOG.md
  src/Data/constants.data.ts
  src/Data/services.data.ts
  src/Views/Layout/ShareModal/index.tsx
  src/Views/Pages/GetButton/index.tsx
  src/Views/Pages/Share/index.tsx
Labels: enhancement, fix
